apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: thearaseng/kub-network-demo-auth:0.0.1

