apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: thearaseng/kub-network-demo-user:0.0.3
        env:
          - name: AUTH_ADDRESS
            value: localhost
      - name: auth
        image: thearaseng/kub-network-demo-auth:0.0.1

